/**
 * SPDX-FileCopyrightText: © 2023 Leandre Gohy <leandre.gohy@hexeo.be>
 * SPDX-License-Identifier: AGPL-3.0-only
 */

#include <stdint.h>
#include <stdarg.h>
#include "print.h"
#include "video.h"
#include "io.h"
#include "mem.h"
#include "font.h"

// The glyphs are FONT_GLYPH_WIDTH wide but advance one pixel less, so adjacent
// characters share a column of inter-letter spacing. font.h is generated by
// tools/fontgen and does not carry the advance, so it lives here.
#define FONT_ADVANCE (6)

uint16_t _fgcolor = 0x7FFF;
uint16_t _bgcolor = 0xAAAA;
static uint16_t _x = 0;
static uint16_t _y = 0;
static uint8_t _scale = 1;

void set_text_color(register uint16_t fgcolor, register uint16_t bgcolor)
{
    _fgcolor = fgcolor;
    _bgcolor = bgcolor;
}

void set_text_scale(register const uint8_t scale)
{
    _scale = (scale == 0) ? 1 : scale;
}

uint16_t text_width(register const char *str)
{
    register uint16_t count = 0;
    while (*str != 0)
    {
        count++;
        str++;
    }

    if (count == 0)
    {
        return 0;
    }

    // The last glyph contributes its full width, every other one its advance.
    return (((count - 1) * FONT_ADVANCE) + FONT_GLYPH_WIDTH) * _scale;
}

void set_xy(register const uint16_t x, register const uint16_t y)
{
    _x = x;
    _y = y;

#if defined(VIDEO_STRICT_BOUND_CHECK)
    if (_x >= 320)
    {
        _x %= 320;
    }
#endif
}

void putchar_(register const char c)
{
    if (c < 32 || c > 126)
    {
        return;
    }

    register uint64_t pixels = *(uint64_t *)&font[(c - 32) * 8];

    if (_scale > 1)
    {
        // Each glyph pixel becomes a _scale x _scale block. Kept off the 1:1 path
        // below, which is the one that runs for every status line at boot.
        const uint16_t fgcolor = _fgcolor;
        const uint16_t bgcolor = _bgcolor;
        const uint8_t scale = _scale;

        for (uint8_t py = 0; py < FONT_GLYPH_HEIGHT; py++)
        {
            for (uint8_t px = 0; px < FONT_GLYPH_WIDTH; px++)
            {
                const bool ink = (pixels & 0x8000000000000000ULL) != 0;
                pixels <<= 1;

                if (!ink && bgcolor == 0xAAAA)
                {
                    continue;
                }

                const uint16_t color = ink ? fgcolor : bgcolor;
                for (uint8_t sy = 0; sy < scale; sy++)
                {
                    uint16_t *block = video_get_ptr(_x + (px * scale), _y + (py * scale) + sy);
                    for (uint8_t sx = 0; sx < scale; sx++)
                    {
                        *block++ = color;
                    }
                }
            }
        }

        _x += FONT_ADVANCE * scale;
        return;
    }

    register uint16_t *ptr = video_get_ptr(_x, _y);

    // ptr is a uint16_t* and _fgcolor/_bgcolor are uint16_t globals, so the
    // compiler must assume a store through ptr can alias them and reload both
    // after every pixel. Copy them into locals once. The transparency test is
    // loop-invariant too, so split it out into two loop variants.
    const uint16_t fgcolor = _fgcolor;
    const uint16_t bgcolor = _bgcolor;

    if (bgcolor == 0xAAAA)
    {
        // Transparent background: only foreground pixels are written, so a
        // blank glyph row costs nothing but the pointer step.
        for (register uint8_t py = 0; py < 9; py++)
        {
            for (register uint8_t px = 0; px < 7; px++)
            {
                if (pixels & 0x8000000000000000ULL)
                {
                    *ptr = fgcolor;
                }
                ptr++;
                pixels <<= 1;
            }
            ptr += 313;
        }
    }
    else
    {
        // Opaque background: every pixel is written either way.
        for (register uint8_t py = 0; py < 9; py++)
        {
            for (register uint8_t px = 0; px < 7; px++)
            {
                *ptr = (pixels & 0x8000000000000000ULL) ? fgcolor : bgcolor;
                ptr++;
                pixels <<= 1;
            }
            ptr += 313;
        }
    }

    _x += FONT_ADVANCE;
#if defined(VIDEO_STRICT_BOUND_CHECK)
    if (_x >= 320)
    {
        _x -= 320;
    }
#endif
}

void print_str(register const char *str)
{
    while (*str != 0)
    {
        putchar_(*str);
        str++;
    }
}

void print_xy(register const uint16_t x, register const uint16_t y, const char *str)
{
    set_xy(x, y);
    print_str(str);
}

void print_center(register const uint16_t cx, register const uint16_t y, const char *str)
{
    const uint16_t width = text_width(str);
    print_xy((width / 2 > cx) ? 0 : (cx - (width / 2)), y, str);
}

void print_dec(register int64_t val)
{
    static uint64_t ranks[] = {0, 1ULL, 10ULL, 100ULL, 1000ULL, 10000ULL, 100000ULL, 1000000ULL, 10000000ULL, 100000000ULL, 1000000000ULL, 10000000000ULL, 100000000000ULL, 1000000000000ULL, 10000000000000ULL, 100000000000000ULL, 1000000000000000ULL, 10000000000000000ULL, 100000000000000000ULL, 1000000000000000000ULL, 10000000000000000000ULL, 0xFFFFFFFFFFFFFFFFULL};

    if (val < 0)
    {
        putchar_('-');
        val = -val;
    }

    register uint64_t value = (uint64_t)val;

    if ((int64_t)value < 0)
    {
        return print_str("9223372036854775808");
    }

    if (value == 0)
    {
        return putchar_('0');
    }

    register uint64_t *p = ranks;
    while (*p <= value)
    {
        p++;
    }

    register uint64_t rank = *(--p);
    do
    {
        register char c = '0';
        while (rank <= value)
        {
            value -= rank;
            c++;
        }
        putchar_(c);
        rank = *(--p);
    } while ((value != 0) || (rank != 0));
}

static inline void __attribute__((always_inline)) print_hex_char(register uint8_t val)
{
    val &= 0x0f;
    if (val >= 10)
    {
        val += 0x7;
    }
    putchar_(val + 0x30);
}

void print_hex(register uint64_t val, register uint8_t bits)
{
    print_str("0x");
    val <<= (64 - bits);
    while (bits > 0)
    {
        print_hex_char(val >> 60);
        val <<= 4;
        bits -= 4;
    }
}
